name: g365_widgets_user
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

flutter:
  uses-material-design: true
  assets:
    - assets/imgs/
    - assets/svg/
